version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: whatsapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data: